import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Define all markets with complete data
const MARKETS_DATA = [
  // Core EUCAN Markets
  {
    code: 'de',
    name: 'Germany',
    region: 'Europe',
    country: 'Germany',
    countryCode: 'DE',
    language: 'German',
    languageCode: 'de-DE',
    websiteUrl: 'https://www.ueber-gewicht.de/',
    sitemapUrl: 'https://www.ueber-gewicht.de/sitemap.xml',
    domain: 'ueber-gewicht.de',
    timezone: 'Europe/Berlin',
    flag: '🇩🇪',
    isCore: true,
    priority: 1,
  },
  {
    code: 'fr',
    name: 'France',
    region: 'Europe',
    country: 'France',
    countryCode: 'FR',
    language: 'French',
    languageCode: 'fr-FR',
    websiteUrl: 'https://www.audeladupoids.fr/',
    sitemapUrl: 'https://www.audeladupoids.fr/sitemap.xml',
    domain: 'audeladupoids.fr',
    timezone: 'Europe/Paris',
    flag: '🇫🇷',
    isCore: true,
    priority: 2,
  },
  {
    code: 'it',
    name: 'Italy',
    region: 'Europe',
    country: 'Italy',
    countryCode: 'IT',
    language: 'Italian',
    languageCode: 'it-IT',
    websiteUrl: 'https://www.novoio.it/',
    sitemapUrl: 'https://www.novoio.it/sitemap.xml',
    domain: 'novoio.it',
    timezone: 'Europe/Rome',
    flag: '🇮🇹',
    isCore: true,
    priority: 3,
  },
  {
    code: 'es',
    name: 'Spain',
    region: 'Europe',
    country: 'Spain',
    countryCode: 'ES',
    language: 'Spanish',
    languageCode: 'es-ES',
    websiteUrl: 'https://www.laverdaddesupeso.es/',
    sitemapUrl: 'https://www.laverdaddesupeso.es/sitemap.xml',
    domain: 'laverdaddesupeso.es',
    timezone: 'Europe/Madrid',
    flag: '🇪🇸',
    isCore: true,
    priority: 4,
  },
  {
    code: 'ca_en',
    name: 'Canada English',
    region: 'North America',
    country: 'Canada',
    countryCode: 'CA',
    language: 'English',
    languageCode: 'en-CA',
    websiteUrl: 'https://www.truthaboutweight.ca/en/',
    sitemapUrl: 'https://www.truthaboutweight.ca/sitemap.xml',
    domain: 'truthaboutweight.ca',
    timezone: 'America/Toronto',
    flag: '🇨🇦',
    isCore: true,
    priority: 5,
  },
  {
    code: 'ca_fr',
    name: 'Canada French',
    region: 'North America',
    country: 'Canada',
    countryCode: 'CA',
    language: 'French',
    languageCode: 'fr-CA',
    websiteUrl: 'https://www.truthaboutweight.ca/fr/',
    sitemapUrl: 'https://www.truthaboutweight.ca/sitemap.xml',
    domain: 'truthaboutweight.ca',
    timezone: 'America/Toronto',
    flag: '🇨🇦',
    isCore: true,
    priority: 6,
  },
  // UK - if it exists
  {
    code: 'uk',
    name: 'United Kingdom',
    region: 'Europe',
    country: 'United Kingdom',
    countryCode: 'GB',
    language: 'English',
    languageCode: 'en-GB',
    websiteUrl: 'https://www.truthaboutweight.uk/',
    sitemapUrl: 'https://www.truthaboutweight.uk/sitemap.xml',
    domain: 'truthaboutweight.uk',
    timezone: 'Europe/London',
    flag: '🇬🇧',
    isCore: true,
    priority: 7,
  },
  // Poland - if it exists
  {
    code: 'pl',
    name: 'Poland',
    region: 'Europe',
    country: 'Poland',
    countryCode: 'PL',
    language: 'Polish',
    languageCode: 'pl-PL',
    websiteUrl: 'https://www.truthaboutweight.pl/',
    sitemapUrl: 'https://www.truthaboutweight.pl/sitemap.xml',
    domain: 'truthaboutweight.pl',
    timezone: 'Europe/Warsaw',
    flag: '🇵🇱',
    isCore: true,
    priority: 8,
  },
  // Switzerland multilingual
  {
    code: 'ch_de',
    name: 'Switzerland German',
    region: 'Europe',
    country: 'Switzerland',
    countryCode: 'CH',
    language: 'German',
    languageCode: 'de-CH',
    websiteUrl: 'https://www.meingewichtverstehen.ch/',
    sitemapUrl: 'https://www.meingewichtverstehen.ch/sitemap.xml',
    domain: 'meingewichtverstehen.ch',
    timezone: 'Europe/Zurich',
    flag: '🇨🇭',
    isCore: false,
    priority: 20,
  },
  {
    code: 'ch_it',
    name: 'Switzerland Italian',
    region: 'Europe',
    country: 'Switzerland',
    countryCode: 'CH',
    language: 'Italian',
    languageCode: 'it-CH',
    websiteUrl: 'https://www.laveritasulpeso.ch/',
    sitemapUrl: 'https://www.laveritasulpeso.ch/sitemap.xml',
    domain: 'laveritasulpeso.ch',
    timezone: 'Europe/Zurich',
    flag: '🇨🇭',
    isCore: false,
    priority: 21,
  },
  {
    code: 'ch_fr',
    name: 'Switzerland French',
    region: 'Europe',
    country: 'Switzerland',
    countryCode: 'CH',
    language: 'French',
    languageCode: 'fr-CH',
    websiteUrl: 'https://www.laveritesurlepoids.ch/',
    sitemapUrl: 'https://www.laveritesurlepoids.ch/sitemap.xml',
    domain: 'laveritesurlepoids.ch',
    timezone: 'Europe/Zurich',
    flag: '🇨🇭',
    isCore: false,
    priority: 22,
  },
  // Nordics
  {
    code: 'se',
    name: 'Sweden',
    region: 'Europe',
    country: 'Sweden',
    countryCode: 'SE',
    language: 'Swedish',
    languageCode: 'sv-SE',
    websiteUrl: 'https://www.meromobesitas.se/',
    sitemapUrl: 'https://www.meromobesitas.se/sitemap.xml',
    domain: 'meromobesitas.se',
    timezone: 'Europe/Stockholm',
    flag: '🇸🇪',
    isCore: false,
    priority: 30,
  },
  {
    code: 'no',
    name: 'Norway',
    region: 'Europe',
    country: 'Norway',
    countryCode: 'NO',
    language: 'Norwegian',
    languageCode: 'no-NO',
    websiteUrl: 'https://www.snakkomvekt.no/',
    sitemapUrl: 'https://www.snakkomvekt.no/sitemap.xml',
    domain: 'snakkomvekt.no',
    timezone: 'Europe/Oslo',
    flag: '🇳🇴',
    isCore: false,
    priority: 31,
  },
  // Baltics
  {
    code: 'lv',
    name: 'Latvia',
    region: 'Europe',
    country: 'Latvia',
    countryCode: 'LV',
    language: 'Latvian',
    languageCode: 'lv-LV',
    websiteUrl: 'https://www.manssvars.lv/',
    sitemapUrl: 'https://www.manssvars.lv/sitemap.xml',
    domain: 'manssvars.lv',
    timezone: 'Europe/Riga',
    flag: '🇱🇻',
    isCore: false,
    priority: 40,
  },
  {
    code: 'ee',
    name: 'Estonia',
    region: 'Europe',
    country: 'Estonia',
    countryCode: 'EE',
    language: 'Estonian',
    languageCode: 'et-EE',
    websiteUrl: 'https://www.minukaal.ee/',
    sitemapUrl: 'https://www.minukaal.ee/sitemap.xml',
    domain: 'minukaal.ee',
    timezone: 'Europe/Tallinn',
    flag: '🇪🇪',
    isCore: false,
    priority: 41,
  },
  {
    code: 'lt',
    name: 'Lithuania',
    region: 'Europe',
    country: 'Lithuania',
    countryCode: 'LT',
    language: 'Lithuanian',
    languageCode: 'lt-LT',
    websiteUrl: 'https://www.manosvoris.lt/',
    sitemapUrl: 'https://www.manosvoris.lt/sitemap.xml',
    domain: 'manosvoris.lt',
    timezone: 'Europe/Vilnius',
    flag: '🇱🇹',
    isCore: false,
    priority: 42,
  },
  // Croatia
  {
    code: 'hr',
    name: 'Croatia',
    region: 'Europe',
    country: 'Croatia',
    countryCode: 'HR',
    language: 'Croatian',
    languageCode: 'hr-HR',
    websiteUrl: 'https://www.istinaodebljini.hr/',
    sitemapUrl: 'https://www.istinaodebljini.hr/sitemap.xml',
    domain: 'istinaodebljini.hr',
    timezone: 'Europe/Zagreb',
    flag: '🇭🇷',
    isCore: false,
    priority: 50,
  },
  // Global domain markets
  {
    code: 'be_nl',
    name: 'Belgium Dutch',
    region: 'Europe',
    country: 'Belgium',
    countryCode: 'BE',
    language: 'Dutch',
    languageCode: 'nl-BE',
    websiteUrl: 'https://www.truthaboutweight.global/be/nl.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Brussels',
    flag: '🇧🇪',
    isCore: false,
    priority: 60,
  },
  {
    code: 'be_fr',
    name: 'Belgium French',
    region: 'Europe',
    country: 'Belgium',
    countryCode: 'BE',
    language: 'French',
    languageCode: 'fr-BE',
    websiteUrl: 'https://www.truthaboutweight.global/be/fr.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Brussels',
    flag: '🇧🇪',
    isCore: false,
    priority: 61,
  },
  {
    code: 'bg',
    name: 'Bulgaria',
    region: 'Europe',
    country: 'Bulgaria',
    countryCode: 'BG',
    language: 'Bulgarian',
    languageCode: 'bg-BG',
    websiteUrl: 'https://www.truthaboutweight.global/bg/bg.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Sofia',
    flag: '🇧🇬',
    isCore: false,
    priority: 62,
  },
  {
    code: 'fi',
    name: 'Finland',
    region: 'Europe',
    country: 'Finland',
    countryCode: 'FI',
    language: 'Finnish',
    languageCode: 'fi-FI',
    websiteUrl: 'https://www.truthaboutweight.global/fi/fi.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Helsinki',
    flag: '🇫🇮',
    isCore: false,
    priority: 63,
  },
  {
    code: 'gr',
    name: 'Greece',
    region: 'Europe',
    country: 'Greece',
    countryCode: 'GR',
    language: 'Greek',
    languageCode: 'el-GR',
    websiteUrl: 'https://www.truthaboutweight.global/gr/el.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Athens',
    flag: '🇬🇷',
    isCore: false,
    priority: 64,
  },
  {
    code: 'hu',
    name: 'Hungary',
    region: 'Europe',
    country: 'Hungary',
    countryCode: 'HU',
    language: 'Hungarian',
    languageCode: 'hu-HU',
    websiteUrl: 'https://www.truthaboutweight.global/hu/hu.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Budapest',
    flag: '🇭🇺',
    isCore: false,
    priority: 65,
  },
  {
    code: 'is',
    name: 'Iceland',
    region: 'Europe',
    country: 'Iceland',
    countryCode: 'IS',
    language: 'Icelandic',
    languageCode: 'is-IS',
    websiteUrl: 'https://www.truthaboutweight.global/is/is.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Atlantic/Reykjavik',
    flag: '🇮🇸',
    isCore: false,
    priority: 66,
  },
  {
    code: 'ie',
    name: 'Ireland',
    region: 'Europe',
    country: 'Ireland',
    countryCode: 'IE',
    language: 'English',
    languageCode: 'en-IE',
    websiteUrl: 'https://www.truthaboutweight.global/ie/en.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Dublin',
    flag: '🇮🇪',
    isCore: false,
    priority: 67,
  },
  {
    code: 'sk',
    name: 'Slovakia',
    region: 'Europe',
    country: 'Slovakia',
    countryCode: 'SK',
    language: 'Slovak',
    languageCode: 'sk-SK',
    websiteUrl: 'https://www.truthaboutweight.global/sk/sk.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Bratislava',
    flag: '🇸🇰',
    isCore: false,
    priority: 68,
  },
  {
    code: 'rs',
    name: 'Serbia',
    region: 'Europe',
    country: 'Serbia',
    countryCode: 'RS',
    language: 'Serbian',
    languageCode: 'sr-RS',
    websiteUrl: 'https://www.truthaboutweight.global/rs/sr.html',
    sitemapUrl: 'https://www.truthaboutweight.global/sitemap.xml',
    domain: 'truthaboutweight.global',
    timezone: 'Europe/Belgrade',
    flag: '🇷🇸',
    isCore: false,
    priority: 69,
  },
];

async function seedMarkets() {
  console.log('🌍 Seeding markets table...');
  
  for (const market of MARKETS_DATA) {
    try {
      await prisma.market.upsert({
        where: { code: market.code },
        update: market,
        create: market,
      });
      console.log(`✅ Seeded market: ${market.name} (${market.code})`);
    } catch (error) {
      console.error(`❌ Failed to seed market ${market.code}:`, error);
    }
  }
  
  const totalMarkets = await prisma.market.count();
  const coreMarkets = await prisma.market.count({ where: { isCore: true } });
  
  console.log(`\n📊 Summary:`);
  console.log(`Total markets: ${totalMarkets}`);
  console.log(`Core markets: ${coreMarkets}`);
  console.log(`Secondary markets: ${totalMarkets - coreMarkets}`);
}

seedMarkets()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });